"""
FHIR R4 Resource Builder.

Converts structured clinical notes and codes into FHIR R4-compliant
JSON resources: Encounter, Condition, Observation, and DocumentReference.
"""

import uuid
from datetime import datetime, timezone
from typing import Optional


def build_fhir_bundle(
    soap_note: dict,
    codes: dict,
    patient_id: str = "synth-patient-001",
    practitioner_id: str = "synth-practitioner-001",
    encounter_date: str | None = None,
) -> dict:
    """
    Build a FHIR R4 Bundle from a structured SOAP note and extracted codes.

    Creates:
    - 1 Encounter resource (the clinical visit)
    - 1 DocumentReference (the full SOAP note as text)
    - N Condition resources (one per ICD-10 code)
    - N Observation resources (for any lab/vital findings)

    Args:
        soap_note: Dict with subjective, objective, assessment, plan.
        codes: Dict with icd10_codes, snomed_codes, cpt_codes.
        patient_id: FHIR Patient ID to reference.
        practitioner_id: FHIR Practitioner ID to reference.
        encounter_date: ISO date string (defaults to now).

    Returns:
        FHIR R4 Bundle as a dict, ready for JSON serialization.
    """
    if not encounter_date:
        encounter_date = datetime.now(timezone.utc).isoformat()

    encounter_id = f"encounter-{_short_uuid()}"
    entries = []

    # ── 1. Encounter Resource ──
    encounter = _build_encounter(
        encounter_id=encounter_id,
        patient_id=patient_id,
        practitioner_id=practitioner_id,
        encounter_date=encounter_date,
        cpt_codes=codes.get("cpt_codes", []),
    )
    entries.append({"resource": encounter, "fullUrl": f"urn:uuid:{encounter_id}"})

    # ── 2. DocumentReference (the full SOAP note) ──
    doc_id = f"docref-{_short_uuid()}"
    doc_ref = _build_document_reference(
        doc_id=doc_id,
        encounter_id=encounter_id,
        patient_id=patient_id,
        soap_note=soap_note,
        encounter_date=encounter_date,
    )
    entries.append({"resource": doc_ref, "fullUrl": f"urn:uuid:{doc_id}"})

    # ── 3. Condition Resources (one per ICD-10 code) ──
    for icd_code in codes.get("icd10_codes", []):
        condition_id = f"condition-{_short_uuid()}"
        condition = _build_condition(
            condition_id=condition_id,
            encounter_id=encounter_id,
            patient_id=patient_id,
            icd_code=icd_code,
            encounter_date=encounter_date,
        )
        entries.append({"resource": condition, "fullUrl": f"urn:uuid:{condition_id}"})

    # ── 4. Build the Bundle ──
    bundle = {
        "resourceType": "Bundle",
        "id": f"smartscribe-bundle-{_short_uuid()}",
        "type": "transaction",
        "timestamp": encounter_date,
        "meta": {
            "lastUpdated": encounter_date,
            "tag": [
                {
                    "system": "http://smartscribe.example.com/tags",
                    "code": "ai-generated",
                    "display": "Generated by SmartScribe AI",
                }
            ],
        },
        "entry": [
            {
                "fullUrl": e["fullUrl"],
                "resource": e["resource"],
                "request": {
                    "method": "POST",
                    "url": e["resource"]["resourceType"],
                },
            }
            for e in entries
        ],
    }

    return bundle


# ──────────────────────────────────────────────
# Resource builders
# ──────────────────────────────────────────────

def _build_encounter(
    encounter_id: str,
    patient_id: str,
    practitioner_id: str,
    encounter_date: str,
    cpt_codes: list[dict],
) -> dict:
    """Build an Encounter resource."""
    encounter = {
        "resourceType": "Encounter",
        "id": encounter_id,
        "status": "finished",
        "class": {
            "system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
            "code": "AMB",
            "display": "ambulatory",
        },
        "subject": {"reference": f"Patient/{patient_id}"},
        "participant": [
            {
                "individual": {"reference": f"Practitioner/{practitioner_id}"},
            }
        ],
        "period": {
            "start": encounter_date,
            "end": encounter_date,
        },
    }

    # Add CPT-based encounter type if available
    if cpt_codes:
        top_cpt = cpt_codes[0]
        encounter["type"] = [
            {
                "coding": [
                    {
                        "system": "http://www.ama-assn.org/go/cpt",
                        "code": top_cpt["code"],
                        "display": top_cpt["display"],
                    }
                ],
            }
        ]

    return encounter


def _build_document_reference(
    doc_id: str,
    encounter_id: str,
    patient_id: str,
    soap_note: dict,
    encounter_date: str,
) -> dict:
    """Build a DocumentReference containing the full SOAP note."""
    # Combine SOAP sections into a single clinical document
    full_note = (
        f"SUBJECTIVE:\n{soap_note.get('subjective', 'Not documented.')}\n\n"
        f"OBJECTIVE:\n{soap_note.get('objective', 'Not documented.')}\n\n"
        f"ASSESSMENT:\n{soap_note.get('assessment', 'Not documented.')}\n\n"
        f"PLAN:\n{soap_note.get('plan', 'Not documented.')}"
    )

    return {
        "resourceType": "DocumentReference",
        "id": doc_id,
        "status": "current",
        "type": {
            "coding": [
                {
                    "system": "http://loinc.org",
                    "code": "11506-3",
                    "display": "Progress note",
                }
            ],
        },
        "subject": {"reference": f"Patient/{patient_id}"},
        "date": encounter_date,
        "context": [
            {"reference": {"reference": f"Encounter/{encounter_id}"}}
        ],
        "content": [
            {
                "attachment": {
                    "contentType": "text/plain",
                    "data": _to_base64(full_note),
                    "title": "Clinical SOAP Note — AI Generated by SmartScribe",
                },
            }
        ],
        "meta": {
            "tag": [
                {
                    "system": "http://smartscribe.example.com/tags",
                    "code": "ai-generated",
                    "display": "Generated by SmartScribe AI",
                }
            ],
        },
    }


def _build_condition(
    condition_id: str,
    encounter_id: str,
    patient_id: str,
    icd_code: dict,
    encounter_date: str,
) -> dict:
    """Build a Condition resource from an ICD-10 code."""
    condition = {
        "resourceType": "Condition",
        "id": condition_id,
        "clinicalStatus": {
            "coding": [
                {
                    "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
                    "code": "active",
                    "display": "Active",
                }
            ],
        },
        "verificationStatus": {
            "coding": [
                {
                    "system": "http://terminology.hl7.org/CodeSystem/condition-ver-status",
                    "code": "provisional",
                    "display": "Provisional",
                }
            ],
        },
        "code": {
            "coding": [
                {
                    "system": "http://hl7.org/fhir/sid/icd-10-cm",
                    "code": icd_code["code"],
                    "display": icd_code["display"],
                }
            ],
            "text": icd_code["display"],
        },
        "subject": {"reference": f"Patient/{patient_id}"},
        "encounter": {"reference": f"Encounter/{encounter_id}"},
        "recordedDate": encounter_date,
        "note": [
            {
                "text": f"AI-suggested code (confidence: {icd_code.get('confidence', 'medium')}). "
                        f"Context: {icd_code.get('context', 'See clinical note.')} "
                        f"— Generated by SmartScribe. Requires clinician verification.",
            }
        ],
    }

    return condition


# ──────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────

def _short_uuid() -> str:
    """Generate a short UUID for resource IDs."""
    return str(uuid.uuid4())[:8]


def _to_base64(text: str) -> str:
    """Encode text to base64 for FHIR attachment."""
    import base64
    return base64.b64encode(text.encode("utf-8")).decode("utf-8")
